services:
  leftover:
    container_name: leftover
    hostname: leftover
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
      - BASE_URL=http://localhost/leftover
      - DATABASE_SERVER=postgresql
      - DATABASE_SERVER_PORT=5432
    volumes:
      - ./leftover:/var/www/leftover:rw
    networks:
      - znet

  apache-leftover:
    container_name: apache-leftover
    hostname: apache-leftover
    image: httpd:2.4
    depends_on:
      - apache-frontproxy
    volumes:
      - ./docker/apache-leftover/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./leftover/public:/var/www/leftover/public:rw
    networks:
      - znet

  apache-frontproxy:
    container_name: apache-frontproxy
    hostname: apache-frontproxy
    image: httpd:2.4
    ports:
        - "80:80"
    volumes:
        - ./docker/apache-frontproxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
        - znet

  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leftover
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - znet

  pgadmin4:
    container_name: pgadmin4
    hostname: pgadmin4
    image: dpage/pgadmin4:6.18
    depends_on: 
      - postgresql
    ports:
      - 8080:80 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./docker/servers.json:/pgadmin4/servers.json:rw
    networks:
      - znet

networks:
  znet:

volumes:
  postgres-data: